### ISSUE TITLE
Gem ownership

### ISSUE THREAD

**Issue by choplin** [fluent-plugins-nursery/fluent-plugin-pgjson#21]
@cosmo0920 I've transferred the ownership to this organization as discussed in #11. Then, you may need the ownership of gem too. If so, could you tell me how I can do that?

**Comment by cosmo0920** [comment]
Could you add gem ownership to okkez and I?

```
gem owner GEM -a okkez000@gmail.com
gem owner GEM -a cosmo0920.oucc@gmail.com
```

**Comment by choplin** [comment]
Oops. Sorry for missing it. I've added the ownership to you.

**Comment by okkez** [comment]
Thanks!
